image: node:latest

stages:
  - test
  - build

cache:
  paths:
  - node_modules/

before_script:
  - yarn install

test-lint:
  stage: test
  script:
    - yarn test:lint

test-unit:
  stage: test
  coverage: '/^Statements\s*:\s*([^%]+)/'
  script:
    - yarn test:unit
  artifacts:
    paths:
      - coverage/

pages:
  stage: build
  script:
    - yarn build
    - gzip -k -6 $(find public/ -type f)
  artifacts:
    paths:
      - public
  only:
    - master
