image: node:latest

stages:
  - test
  - build

cache:
  paths:
  - node_modules/

before_script:
  - yarn install

lint:
  stage: test
  script:
    - yarn test:lint

pages:
  stage: build
  script:
  - yarn build
  - gzip -k -6 $(find public/ -type f)
  artifacts:
    paths:
    - public
  only:
  - master
