image: node:8

stages:
  - build

cache:
  paths:
  - node_modules/

before_script:
  - yarn install

pages:
  stage: build
  variables:
    GA_PROP: $PROD_GA_PROPERTY
  script:
  - BUILD_PATH="$(pwd)/public" yarn gulp build
  - gzip -k -6 $(find public/ -type f)
  artifacts:
    paths:
    - public
  only:
  - master
